import { Weapon } from "../interfaces/sharedInterfaces";

export const weapons: Weapon[] = [
    {
        name: 'rattler',
        type: 'shell',
        color: 'black',
        bulletSize: 2,
        turret: true,
        damage: 0.2,
        impactPower: 4,
        cooldown: 50,
        specials: ['suppressing'],
        cost: 1,
        costInSpeed: 4,
        speed: 15
    },
    {
        name: 'vengeance cannon',
        type: 'shell',
        color: 'black',
        bulletSize: 3,
        turret: true,
        damage: 3,
        impactPower: 6,
        cooldown: 500,
        specials: ['detonate 5'],
        cost: 2,
        costInSpeed: 1,
        speed: 15
    },
    {
        name: 'shreik missiles',
        type: 'missile',
        color: 'white',
        bulletSize: 3,
        turret: true,
        damage: 3,
        impactPower: 6,
        cooldown: 500,
        specials: ['homing'],
        cost: 2,
        costInSpeed: 1,
        speed: 12
    },
    {
        name: 'vanguard',
        type: 'shell',
        color: 'black',
        bulletSize: 2,
        turret: true,
        damage: 1,
        impactPower: 4,
        cooldown: 200,
        specials: ['point blank'],
        cost: 1,
        costInSpeed: 1,
        speed: 15
    },
    {
        name: 'accelerator',
        type: 'shell',
        color: 'black',
        bulletSize: 2,
        turret: true,
        damage: 2,
        impactPower: 4,
        cooldown: 200,
        specials: ['shield piercing'],
        cost: 1,
        costInSpeed: 1,
        speed: 16
    },
    {
        name: 'micro rocket pod',
        type: 'missile',
        color: 'white',
        bulletSize: 2,
        turret: false,
        damage: 0.5,
        impactPower: 3,
        cooldown: 50,
        specials: ['light'],
        cost: 0,
        costInSpeed: 0,
        speed: 12
    },
    {
        name: 'microbeam',
        type: 'energy',
        color: 'cyan',
        bulletSize: 2,
        turret: false,
        damage: 0.5,
        impactPower: 3,
        cooldown: 50,
        specials: ['light'],
        cost: 0,
        costInSpeed: 0,
        speed: 12
    },
    {
        name: 'blaster',
        type: 'shell',
        color: 'black',
        bulletSize: 2,
        turret: false,
        damage: 0.5,
        impactPower: 3,
        cooldown: 50,
        specials: ['light'],
        cost: 0,
        costInSpeed: 0,
        speed: 12
    }
];